services:
  api:
    build: .
    container_name: pokemanager-api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      NODE_ENV: production

  db:
    image: postgres:17-alpine
    container_name: pokemanager-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: pokemanager-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: