services:
  api:
    build: .
    container_name: pokemanager-api
    command: sh -c "npx prisma migrate deploy && node dist/main/server.js"
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    container_name: pokemanager-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    container_name: pokemanager-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: